# Generated by Django 5.0 on 2024-04-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='assigned',
        ),
    ]
