# Generated by Django 4.2.7 on 2023-12-17 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0003_assignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('template', 'proposer')},
        ),
    ]
