# Generated by Django 5.0 on 2023-12-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_proposal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_words',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
