# Generated by Django 4.0 on 2024-02-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_question_max_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
